spring:
  application:
    name: apollo-adminservice
  profiles:
    active: ${apollo_profile}

ctrip:
  appid: 100003172
  
server:
  port: 8090
  
logging:
  file: /Users/xuzhiwu/Desktop/document/apollo-adminservice.log
